-- Importacao escolas Jales - gerado automaticamente
-- Total: 35 escolas
SET NAMES utf8mb4;
-- Cria indice unico no CIE para evitar duplicatas (execute separado se der erro de duplicata, ignore)
-- ALTER TABLE escolas ADD UNIQUE INDEX uniq_codigo (codigo);

INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Coripheu de Azevedo Marques"', '28435', 'e028435a@educacao.sp.gov.br', '3635-1113', 'Aparecida D''Oeste - R. Luís Marchiori, 260 - 324, Aparecida d''Oeste - SP, 15735-000', 'VALDEVILSO PASQUALOTTO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "José dos Santos"', '27259', 'e027259a@educacao.sp.gov.br', '3664-1125', 'Aspásia - R. José Gonçalves Valentim, Aspásia - SP, 15763-000', 'AMAURI BASSETTO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE Profª Maria Pereira de B. Benetoli', '30636', 'e030636a@educacao.sp.gov.br', '3482-1164', 'Auriflama - R. José Barbosa, 60-53 - 60-53 - Jardim São José, Auriflama - SP, 15350-000', 'SUELI KUSSURA MAIA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "João Rodrigues Fernandes"', '30624', 'e030624a@educacao.sp.gov.br', '3482-1411', 'Auriflama - Av. João Rodrigues Fernandes, 6208 - São José, Auriflama - SP, 15350-000', 'EDSON RODRIGUES DE LIMA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE de Osvaldo Ramos', '27170', 'e027170a@educacao.sp.gov.br', '3694-1118', 'Dirce Reis - R. Monteiro Lobato, 2274 - Centro, Dirce Reis - SP, 15715-000', 'CLEUSA RONDELLI CLEMENTE SANCHEZ') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Baptista Dolci"', '27108', 'e027108a@educacao.sp.gov.br', '3636-1145', 'Dolcinópolis - R. Atílio Gonçalves, 1177 - Centro, Dolcinópolis - SP, 15740-000', 'ELAINE SOUZA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Profª Vanir Ferrero Moraes"', '30752', 'e030752a@educacao.sp.gov.br', '3637-1114', 'Guzolândia - R. João Calefi, 340 - Centro, Guzolândia - SP, 15355-000', 'SANDRA ALVARENGA DE SOUZA CARDOSO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Dom Artur Horsthuis"', '27224', 'e027224@educacao.sp.gov.br', '3632-1624', 'Jales - R. Vinte, 2939 - BLOCO 2 - Centro, Jales - SP, 15700-000', 'SILVIA CRISTINA PISSOLITO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('Cel de Jales – EE "Dom Artur Horsthuis"', '985715', 'e027224a@educacao.sp.gov.br', '3632-1624', 'Jales - R. Vinte, 2939 - BLOCO 2 - Centro, Jales - SP, 15700-000', 'SILVIA CRISTINA PISSOLITO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Dr. Euphly Jalles"', '27145', 'e027145a@educacao.sp.gov.br', '3632-1287', 'Jales - R. 2, 2714 - Jardim Trianon, Jales - SP, 15703-104', 'SILVANA CÁSSIA CANHOTO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Prof. Carlos de Arnaldo Silva"', '27261', 'e027261a@educacao.sp.gov.br', '3632-1456', 'Jales - R. Dirce Líbano dos Santos, 2856 - Jardim America, Jales - SP, 15703-112', 'LUIS ESPECIATO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Profª Sueli da Silveira Marin Batista', '49700', 'e049700a@educacao.sp.gov.br', '3632-1625', 'Jales - R. Novo Horizonte, 5128 - Arapuã, Jales - SP, 15700-186', 'MARCIA APARECIDA RODRIGUES') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Juvenal Giraldelli"', '27285', 'e027285a@educacao.sp.gov.br', '3632-1175', 'Jales - R. Otávio Graziane, 1074 - Alto do Ipê, Jales - SP, 15706-054', 'JONAS NEGRO GEREZ SANCHES') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Profª Onélia Faggioni Moreira"', '906104', 'e906104a@educacao.sp.gov.br', '3632-4981', 'Jales - Av. Salustiano Pupim, 708 - Jardim Soraia, Jales - SP, 15704-462', 'ELIANA DE SOUZA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Antonio Marin Cruz"', '28332', 'e028332a@educacao.sp.gov.br', '3695-1123', 'Marinópolis - R. Ceará, 168 - Centro, Marinópolis - SP, 15730-003', 'LUCIANO APARECIDO FEBOLI') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Adelino Bertani"', '27054', 'e027054a@educacao.sp.gov.br', '3638-6202', 'Mesópolis - Rua Gonçalves Siqueira, 1937 - Centro, Mesópolis - SP, 15748-000', 'SELMA MARIA DA SILVA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Profª Maria Pilar Ortega Garcia"', '28320', 'e028320a@educacao.sp.gov.br', '3681-1128', 'Nova Canaã Paulista - Av. Central, S/N, Nova Canaã Paulista - SP, 15773-000', 'JOSÉ ANTONIO TUNUNCIO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Orestes Ferreira de Toledo"', '28344', 'e028344a@educacao.sp.gov.br', '3651-1327', 'Palmeira d''Oeste - R. Mal. Humberto de Alençar Castelo Branco, 1318-1360 - Palmeira d''Oeste, SP, 15720-000', 'SANDRA REGINA ROSA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Prefeito José Ribeiro"', '27194', 'e027194a@educacao.sp.gov.br', '3648-1154', 'Paranapuã - Av. Luizete, 2473 - Centro, Paranapuã - SP, 15745-000', 'MARINANGELA ZEQUINE CAMPOS POLARIN') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Profª Zélia de Lourdes Zaccarelli Lopes"', '27182', 'e027182a@educacao.sp.gov.br', '3699-1102', 'Pontalinda - R. Manoel Néo Carvalho, 1556 - Centro, Pontalinda - SP, 15718-000', 'HORÁCIO DOS REIS MARQUES FERREIRA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Rubens de Oliveira Camargo"', '28381', 'e028381a@educacao.sp.gov.br', '3661-1125', 'Rubinéia - Av. Guimarães Rosa, 40 – Centro, 15790-000', 'VALTER CÍCERO DA SILVA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Carlos Celso Lenarduzzi"', '27112', 'e027112a@educacao.sp.gov.br', '3633-1269', 'Santa Albertina - Av. Guimarães Rosa, 40 - Centro, Rubinéia - SP, 15790-000', 'MARISTELI GONÇALVES TEZZON') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Prefeito Antonio Bezerra de Araújo"', '28393', 'e028393a@educacao.sp.gov.br', '3663-1110', 'Santa Clara d''Oeste - R. Profa. Maria Pardinho da Conceição, 410 - Centro, Santa Clara d''Oeste - SP, 15785-000', 'ELIZANGELA BATISTA DE TOLEDO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Professor Itael de Mattos', '28400', 'e028400a@educacao.sp.gov.br', '3631-1295', 'Santa Fé do Sul - R. Oito, 764 - Centro, Santa Fé do Sul - SP, 15775-000', 'KAREN CRISTINA GAINO ALVES') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('CEL de Santa Fé do Sul', '985806', 'e985806a@educacao.sp.gov.br', '3631-1295', 'Santa Fé do Sul - R. Oito, 764 - Centro, Santa Fé do Sul - SP, 15775-000', 'KAREN CRISTINA GAINO ALVES') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Profª Maria das Dores Ferreira Rocha"', '28289', 'e028289a@educacao.sp.gov.br', '3643-1106', 'Santa Rita d''Oeste - R. Teodomiro Alves Corrêa, 476 - Centro, Santa Rita d''Oeste - SP, 15780-000', 'VÂNIA SCAPIN STAFUZZA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Francisco Molina Molina"', '27133', 'e027133a@educacao.sp.gov.br', '3662-6105', 'Santa Salete - Av. Presidente Roosevelt, s/nº, Santa Salete - SP, 15768-000', 'REGINA MARTA DA SILVA CARDOSO LIMA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Domingos Donato Rivelli"', '28290', 'e028290a@educacao.sp.gov.br', '3692-1124', 'Santana da Ponte Pensa - Av. Santana, 767 - Centro, Santana da Ponte Pensa - SP, 15765-000', 'SILVIA REGINA RODRIGUES') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Oscar Antônio da Costa"', '27066', 'e027066a@educacao.sp.gov.br', '3693-1120', 'São Francisco - Av. Oscár Antônio da Costa, 1075 - Centro, São Francisco - SP, 15710-000', 'EMIRVAINE APARECIDA FERREIRA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Coronel Ernesto Schmidt"', '30582', 'e030582a@educacao.sp.gov.br', '3706-1241', 'Suzanápolis - R. Vinte e Cinco de Janeiro, Suzanápolis - SP, 15380-000', 'ANA CLÁUDIA DIAS CHIQUETO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Prof. José Joaquim dos Santos"', '28319', 'e028319a@educacao.sp.gov.br', '3691-1140', 'Três Fronteiras - Av. Ana Rocha de Oliveira, 705 - Centro, Três Fronteiras - SP, 15770-000', 'FRANCISCO PENHA DELSIM') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Professor Akio Satoru"', '27248', 'e027248a@educacao.sp.gov.br', '3634-1224', 'Urânia - R. Fortaleza, 549 - Centro, Urânia - SP, 15760-000', 'ROSA MARIA PODSCLAN') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "Profª Elide Apparecida Carlos', '909993', 'e909993a@educacao.sp.gov.br', '3634-1466', 'Urânia - Rua Donato Chapichi COHAB B.P.F.Braga, Urânia - SP, 15760-000', 'LUANA PRICILA COCHARRO DE SOUZA') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "José Teixeira do Amaral"', '27212', 'e027212a@educacao.sp.gov.br', '3634-1242', 'Urânia - Rua Boa Esperança, 371 - Centro, Urânia - SP, 15760-000', 'LLUCINEIDE PIGARI DEL PINO') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);
INSERT INTO escolas (nome, codigo, email, telefone, endereco, responsavel) VALUES ('EE "José Nogueira de Souza"', '27169', 'e027169a@educacao.sp.gov.br', '3642-1103', 'Vitória Brasil - R. Dr. Nunes, nº - Centro, Vitória Brasil - SP, 15713-000', 'HELIO FARIA DE SOUZA (Vice Diretor)') ON DUPLICATE KEY UPDATE nome=VALUES(nome), email=VALUES(email), telefone=VALUES(telefone), endereco=VALUES(endereco), responsavel=VALUES(responsavel);